### ISSUE TITLE
Mavo UI Localization

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#378]
Hi Lea!

There are some problems with the localization.
1. While in **Preview mode** the localization works perfectly fine:
![edit](https://user-images.githubusercontent.com/9166277/44914006-8c182800-ad37-11e8-9280-93d0ec7b8d7a.png)
But when I switch to **Edit Mode** an issue appears: ![editing](https://user-images.githubusercontent.com/9166277/44914105-dc8f8580-ad37-11e8-924b-868f432611aa.png) 

There is a corresponding string in the localization file and is translated into Russian but is not used: 
```JavaScript
Mavo.Locale.register("ru", {
  "edit": "Редактировать",
  "editing": "Редактирование",
  ...
});
```
Probably because of the hardcoded string in **mavo.css**:
```CSS
[mv-app][mv-mode="edit"] .mv-bar.mv-ui .mv-edit::after {
  content: "ing";
}
```
2. While in **Edit Mode** if I delete an element, appear the text that is not localized: the hint and the Undo button text
![deleted](https://user-images.githubusercontent.com/9166277/44914545-3fcde780-ad39-11e8-9195-12741cda2f7d.png)
There are corresponding strings in the localization file and are translated into Russian:
```JavaScript
Mavo.Locale.register("ru", {
  ...
	"item-deleted": "Элемент {name} удален",
	"n-items": "{n} {name} элемент(ов)",
	"undo": "Отменить",
  ...
});
```

3. In **mavo.css** there are several fragments of text that are hardcoded and are absent in the localization file:
```CSS
  .mv-message.mv-warning::before {
        content: "⚠️ Warning: ";
}

.mv-message.mv-error::before {
        content: "😳 Oh noes! ";
}

.mv-message::before {
        content: "Notice: ";
}

time[property][aria-label][mv-mode="edit"].mv-empty::before {
        content: "(No " attr(aria-label) ")";
}
```
Thank you very much for your work! You are awesome! 😍
